#!/bin/bash

echo '--------------------------------------------------------------------------------'
echo '|                               Config Install                                 |'
echo '--------------------------------------------------------------------------------'
username=$0
hostname=$1
pass=$2

#   Разблокировка и обновление x32 библиотек'
# 1 -установить, 0 -не устанавливать
x86=0

#   Наcтройка загрузчика
# efi     - установка и настройка только UEFI загрузчика
# grub    - установка и настройка grub без UEFI
# efigrub - установка и настройка grub с поддержкой UEFI
bootmgr=efi

#   Установка поддержки микрокода для процессоров
# amd, intel
ucode=intel

echo '--------------------------------------------------------------------------------'
echo ' Install Arch Linux '$username'@'$hostname
echo '--------------------------------------------------------------------------------'
pacman -Sy sed wget --noconfirm
pacman -S vim vim-plugins --noconfirm

echo '>> Russification...'
loadkeys ru
setfont cyr-sun16
echo -e 'KEYMAP=ru\nFONT=cyr-sun16\n' > /etc/vconsole.conf

sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen

echo -e 'LANG=ru_RU.UTF-8' > /etc/locale.conf
export LANG=ru_RU.UTF-8

echo ">> Синхронизация времени"
timedatectl set-ntp true
echo '>> Настройка времени по UTC'
hwclock --systohc --utc
#echo ">> Настройка часового пояса"
# Настройка часового пояса /usr/share/zoneinfo/Регион/Город
# Список регионов можно посмотреть коммандой
# ls /usr/share/zoneinfo
#timedatectl set-timezone Asia/Almaty
#ln -sf /usr/share/zoneinfo/Asia/Almaty /etc/localtime
timedatectl status

echo '>> Имя компьютера '$hostname
echo $hostname > /etc/hostname
echo -e '127.0.0.1 localhost\n::1 localhost\n' > /etc/hosts

# Настройка администратора и создание пользователя $username
echo '>> Пароль root'
(
	echo $pass
	echo $pass
) | passwd
useradd -G wheel -s /bin/bash -m $username
echo '>> Пароль пользователя '$username
(
	echo $pass
	echo $pass
) | passwd $username

echo '>> Собираем RAM linux'
mkinitcpio -p linux

echo '>> Настройка прав администратора'
# Запрашивать пароль при выполненинии sudo
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers
# Выполнять sudo без запроса пароля
#echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
chown -R $username:users /home/$username/

echo '>>  Настройка pacman'
sed -i 's/#Color/Color/g' /etc/pacman.conf

if (( $x86 == 1 )); then
	echo '>> Разблокировка и обновление x32 библиотек'
	echo -e '[multilib]\nInclude = /etc/pacman.d/mirrorlist\n' >> /etc/pacman.conf
fi

echo '>> Установка загрузчика и микрокода'
case $ucode in
	intel)
		echo 'установка микрокода для intel'
		pacman -Sy intel-ucode --noconfirm
		;;
	amd) 
		echo 'установка микрокода для amd'
		pacman -Sy amd-ucode --noconfirm
		;;
	*)
		echo 'установка микрокода не требуется'
		;;
esac

case $bootmgr in
	efi)
		echo 'установка EFI'
		pacman -Sy efibootmgr --noconfirm
		bootctl install
		echo -e 'default arch\ntimeout 0\neditor 1' > /boot/loader/loader.conf
		echo 'title Arch Linux' > /boot/loader/entries/arch.conf
		echo 'linux /vmlinuz-linux' >> /boot/loader/entries/arch.conf
		case $ucode in
			intel)
				echo 'initrd /intel-ucode.img' >> /boot/loader/entries/arch.conf
				;;
			amd) 
				echo 'initrd /amd-ucode.img' >> /boot/loader/entries/arch.conf
				;;
			*)
				;;
		esac
		echo 'initrd /initramfs-linux.img' >> /boot/loader/entries/arch.conf
		echo 'options root=/dev/sda3 rw' >> /boot/loader/entries/arch.conf          
		;;
	grub) 
		echo 'установка GRUB'
		pacman -Sy grub --noconfirm 
		grub-install /dev/sda
		grub-mkconfig -o /boot/grub/grub.cfg
		sed -i 's/set timeout=5/set timeout=0/g' /boot/grub/grub.cfg
		;;
	efigrub)
		echo 'установка GRUB'
		pacman -Sy efibootmgr grub --noconfirm 
		grub-install /dev/sda
		grub-mkconfig -o /boot/grub/grub.cfg
		sed -i 's/set timeout=5/set timeout=0/g' /boot/grub/grub.cfg          
		;;
	*)
		echo 'загрузчик не установлен'
		;;
esac
echo '--------------------------------------------------'
echo '|            Установка оболочки zsh              |'
echo '--------------------------------------------------'
pacman -Sy zsh zsh-completions zsh-syntax-highlighting zsh-autosuggestions grml-zsh-config --noconfirm
chsh -s /bin/zsh
chsh -s /bin/zsh $username
echo 'source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh' >> /etc/zsh/zshrc
echo 'source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' >> /etc/zsh/zshrc

cd /root/
wget 'https://raw.githubusercontent.com/like913/arch-install/master/config/.zshrc'
sed -i "s/zstyle :compinstall filename '/home/user/.zshrc'/zstyle :compinstall filename '/root/.zshrc'/g" .zshrc
echo "PROMPT='%F{red}%n%f@%F{248}%m%f %F{white}%B%~%b%f # '" >> .zshrc

cd /home/$username/
wget 'https://raw.githubusercontent.com/like913/arch-install/master/config/.zshrc'
sed -i "s/zstyle :compinstall filename '/home/user/.zshrc'/zstyle :compinstall filename '/home/$username/.zshrc'/g" .zshrc
echo "PROMPT='%F{blue}%n%f@%F{248}%m%f %F{white}%B%~%b%f # '" >> .zshrc
chown -R $username:users .zshrc

echo '--------------------------------------------------------------------------------'
echo '|                    Установка пользовательских приложений                     |'
echo '--------------------------------------------------------------------------------'
sudo -u $username sh /home/$username/install.sh $pass

echo '>> Отчистка диска'
pacman -Scc --noconfirm

exit
