#!/bin/bash

echo '--------------------------------------------------------------------------------'
echo '|                               Config Install                                 |'
echo '--------------------------------------------------------------------------------'
username=$0
hostname=$1

#   Разблокировка и обновление x32 библиотек'
# 1 -установить, 0 -не устанавливать
x86=1

#   Наcтройка загрузчика
# efi     - установка и настройка только UEFI загрузчика
# grub    - установка и настройка grub без UEFI
# efigrub - установка и настройка grub с поддержкой UEFI
bootmgr=grub
#   Установка поддержки микрокода для процессоров
# amd, intel
ucode=intel

# Функция установки из aur
#Входящие параметры $1 наименование пакета
function aur {
cd /tmp
git clone https://aur.archlinux.org/$1.git
chown -R $username:users /tmp/$1
chown -R $username:users /tmp/$1/PKGBUILD
cd $1
sudo -u $username makepkg -si --noconfirm
cd ..
rm -rf $1
}

echo '--------------------------------------------------------------------------------'
echo ' Install Arch Linux '$username'@'$hostname
echo '--------------------------------------------------------------------------------'
pacman -Sy sed --noconfirm

echo '>> Russification...'
loadkeys ru
setfont cyr-sun16
echo -e 'KEYMAP=ru\nFONT=cyr-sun16\n' > /etc/vconsole.conf

sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen

echo -e 'LANG=ru_RU.UTF-8' > /etc/locale.conf
export LANG=ru_RU.UTF-8

echo '>> Настройка времени по UTC'
timedatectl set-ntp true
hwclock --systohc --utc
timedatectl status

echo '>> Имя компьютера '$hostname
echo $hostname > /etc/hostname
echo -e '127.0.0.1 localhost\n::1 localhost\n' > /etc/hosts

# Настройка администратора и создание пользователя $username
echo '>> Пароль root'
passwd
useradd -G wheel -s /bin/bash -m $username
echo '>> Пароль пользователя '$username
passwd $username

echo '>> Собираем RAM linux'
mkinitcpio -p linux

echo '>> Настройка прав администратора'
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers
sed -i 's/#Color/Color/g' /etc/pacman.conf

if (( $x86 == 1 )); then
    echo '>> Разблокировка и обновление x32 библиотек'
    echo -e '[multilib]\nInclude = /etc/pacman.d/mirrorlist\n' >> /etc/pacman.conf
fi

pacman -Sy

echo '>> Установка загрузчика и микрокода'
case $ucode in
     intel)
          echo 'установка микрокода для intel'
          pacman -Sy intel-ucode --noconfirm
          ;;
     amd) 
          echo 'установка микрокода для amd'
          pacman -Sy amd-ucode --noconfirm
          ;;
     *)
          echo 'установка микрокода не требуется'
          ;;
esac

case $bootmgr in
     efi)
          echo 'установка EFI'
          pacman -Sy efibootmgr --noconfirm
          bootctl install
          echo -e 'default arch\ntimeout 0\neditor 1' > /boot/loader/loader.conf
          echo 'title Arch Linux' > /boot/loader/entries/arch.conf
          echo 'linux /vmlinuz-linux' >> /boot/loader/entries/arch.conf
          case $ucode in
              intel)
                  echo 'initrd /intel-ucode.img' >> /boot/loader/entries/arch.conf
                  ;;
              amd) 
                  echo 'initrd /amd-ucode.img' >> /boot/loader/entries/arch.conf
                  ;;
              *)
                  ;;
          esac
          echo 'initrd /initramfs-linux.img' >> /boot/loader/entries/arch.conf
          echo 'options root=/dev/sda3 rw' >> /boot/loader/entries/arch.conf          
          ;;
     grub) 
          echo 'установка GRUB'
          pacman -Sy grub --noconfirm 
          grub-install /dev/sda
          grub-mkconfig -o /boot/grub/grub.cfg
          sed -i 's/set timeout=5/set timeout=0/g' /boot/grub/grub.cfg
          ;;
     efigrub)
          echo 'установка GRUB'
          pacman -Sy efibootmgr grub --noconfirm 
          grub-install /dev/sda
          grub-mkconfig -o /boot/grub/grub.cfg
          sed -i 's/set timeout=5/set timeout=0/g' /boot/grub/grub.cfg          
          ;;
     *)
          echo 'загрузчик не установлен'
          ;;
esac

pacman -S zsh zsh-completions
chsh -l
chsh -s '/bin/zsh'

echo '--------------------------------------------------'
echo '|              Установка драйверов               |'
echo '--------------------------------------------------'

echo '>> Установка xorg и mesa'
pacman -Sy xorg-server xorg-xinit mesa --noconfirm

mkdir -p /etc/X11/xorg.conf.d
cd /etc/X11/xorg.conf.d/

#echo 'Тачпад'
#pacman -Sy xf86-input-synaptics --noconfirm
#wget 'https://raw.githubusercontent.com/like913/arch-install/master/config/X11/10-synaptics.conf'

echo '>> Установка поддержки файловых систем NTFS exFAT'
pacman -Sy ntfs-3g exfat-utils --noconfirm

#echo '>> Видеокарта'
#echo 'intel'
#pacman -Sy xf86-video-intel --noconfirm
#wget 'https://raw.githubusercontent.com/like913/arch-install/master/config/20-intel.conf'
#echo 'Настрока DRM'
#sed -i 's/MODULES=(/MODULES=(i915 /g' /etc/mkinitcpio.conf

#echo 'nvidia'
#pacman -Sy nvidia nvidia-utils lib32-nvidia-utils nvidia-settings --noconfirm
#echo '>> Настрока DRM nVidia'
#sed -i 's/MODULES=(/MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm /g' /etc/mkinitcpio.conf
## После перезагрузки выполнить sudo nvidia-xconfig для настройки видеокары
## sudo nvidia-xconfig --prime необходимо для конфигурирования драйвера в совместимом режиме с картой intel
#wget 'https://raw.githubusercontent.com/like913/arch-install/master/config/20-nvidia.conf'

#echo 'AMD' #Установка и настройка AMD не тестировалось
#pacman -Sy xf86-video-amdgpu --noconfirm

echo '>> VirtualBox'
pacman -Sy virtualbox-guest-utils --noconfirm

echo '--------------------------------------------------'
echo '|           Установка Display Manager            |'
echo '--------------------------------------------------'
# раскомментировать блок SDDM или LXDM
echo '>> Установка sddm'
pacman -Sy sddm sddm-kcm --noconfirm
systemctl enable sddm

#echo '>> Настройка SDDM для nVidia PRIME'
#echo 'xrandr --setprovideroutputsource modesetting NVIDIA-0' >> /usr/share/sddm/scripts/Xsetup
echo 'xrandr --auto' >> /usr/share/sddm/scripts/Xsetup
echo 'xrandr --dpi 75' >> /usr/share/sddm/scripts/Xsetup

#echo 'Установка lxdm'
#pacman -Sy lxdm --noconfirm
#systemctl enable lxdm

echo '>> Установка настройки сети'
pacman -Sy networkmanager --noconfirm
systemctl enable NetworkManager

echo '--------------------------------------------------'
echo '|         Установка Desktop Environment          |'
echo '--------------------------------------------------'
#echo '>> Cinnamon'
#pacman -Sy cinnamon cinnamon-translations --noconfirm
#pacman -Sy gnomme-terminal

#echo '>> Deepin'
#pacman -Sy deepin --noconfirm

echo '>> KDE Plasma'
pacman -Sy phonon-qt5-vlc --noconfirm
pacman -Sy plasma-meta kdebase packagekit-qt5 --noconfirm
echo '>  Дополнительный софт для KDE'
pacman -Sy konsole partitionmanager ark spectacle okular --noconfirm
pacman -Rsnc konqueror kwrite --noconfirm

#echo '>> Bluetooth pulseaudio и alsa поддержка звука'
#pacman -Sy bluez bluez-utils bluedevil pulseaudio-bluetooth alsa-utils pulseaudio-equalizer-ladspa --noconfirm
#systemctl enable bluetooth.service

#echo 'XFCE'
#pacman -Sy xfce4 xfce4-goodies --noconfirm

echo '--------------------------------------------------'
echo '|        Установка дополнительного софта         |'
echo '--------------------------------------------------'
cd /root/
wget 'https://raw.githubusercontent.com/like913/arch-install/master/config/.zshrc'
sed -i "s/PROMPT='%F{blue}%n%f@%F{248}%m%f %F{white}%B%~%b%f # '/PROMPT='%F{red}%n%f@%F{248}%m%f %F{white}%B%~%b%f # '/g" .zshrc
cd /home/$username/.bashrc
wget 'https://raw.githubusercontent.com/like913/arch-install/master/config/.zshrc'

echo '>> Настройка папок пользователя'
pacman -Sy xdg-user-dirs --noconfirm

pacman -Syu
pacman -Sy git --noconfirm

echo '>> Установка pacaur'
aur auracle-git
aur pacaur

#echo '>> Установка микрокода для aic94xx и wd719x'
#sudo -u $username pacaur -S aic94xx-firmware wd719x-firmware
#aur aic94xx-firmware
#aur wd719x-firmware

mkinitcpio -p linux

echo '>> Установка octopi'
aur alpm_octopi_utils
aur octopi

echo '>> Установка Firewall'
pacman -Sy ufw gufw --noconfirm
systemctl enable ufw.service

#echo '>> Установка wine'
#pacman -Sy wine wine-mono wine_gecko winetricks --noconfirm
#aur d9vk-bin
#aur dxvk-bin
#winecfg
#setup_d9vk install
#setup_dxvk install
#pacman -Sy vkd3d lib32-vkd3d --noconfirm

echo '>> Установка firefox'
pacman -Sy firefox firefox-i18n-ru --noconfirm
pacman -Sy thunderbird thunderbird-i18n-ru --noconfirm

echo '>> Установка VLC'
pacman -Sy vlc cheese --noconfirm

echo '>> Установка qbittorrent'
pacman -Sy qbittorrent --noconfirm

echo '>> Читалки, просмотр фото, музыки и прочее'
pacman -Sy neofetch baobab --noconfirm
pacman -Sy gpicview audacious --noconfirm

echo '>> Ставим шрифты'
pacman -Sy ttf-liberation ttf-dejavu --noconfirm
aur ttf-ms-fonts
aur ttf-tahoma

echo '>> Отчистка диска'
pacman -Sycc --noconfirm
exit
