#!/bin/bash

echo '--------------------------------------------------'
echo '|                Config Install                  |'
echo '--------------------------------------------------'
username="like"
hostname="E5-576G"
pass='123'

echo '--------------------------------------------------'
echo '|              Install Arch Linux                |'
echo '--------------------------------------------------'
echo 'Install Arch Linux '$username'@'$hostname
echo '--------------------------------------------------'
pacman -Sy sed reflector --noconfirm

echo '>> Russification...'
loadkeys ru
setfont cyr-sun16
echo -e 'KEYMAP=ru\nFONT=cyr-sun16\n' > /etc/vconsole.conf

sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen

export LANG=ru_RU.UTF-8

echo ">> Синхронизация времени"
timedatectl set-ntp true
timedatectl status

echo -e "\n"
echo '--------------------------------------------------'
echo '|             Форматирование диска               |'
echo '--------------------------------------------------'

sfdisk /dev/sda < hdd1tlw.dump
fdisk -l

echo 'y' | mkswap /dev/sda1 -L swap
swapon /dev/sda1

echo 'y' | mkfs.ext4 /dev/sda3 -L Arch
mount /dev/sda3 /mnt

echo 'y' | mkfs.fat -F32 /dev/sda2 -n EFI
mkdir -p /mnt/boot
mount /dev/sda2 /mnt/boot

echo 'y' | mkfs.ext4 /dev/sda5 -L home
mkdir -p /mnt/home
mount /dev/sda5 /mnt/home

echo 'y' | nkfs.ntfs -Q /dev/sda4 -L win
mkdir -p /mnt/mnt/win
mount /dev/sda4 /mnt/mnt/win

echo 'y' | nkfs.ntfs -Q /dev/sda6 -L public
mkdir -p /mnt/mnt/public
mount /dev/sda6 /mnt/mnt/public

echo '--------------------------------------------------'
echo '|             Установка Arch Linux               |'
echo '--------------------------------------------------'
echo ">> Настройка Зеркал"
reflector --country Russia --country Kazakhstan --age 12 --sort rate --save /etc/pacman.d/mirrorlist

echo '>> Установка Arch GNU'
pacstrap -i /mnt base base-devel linux linux-firmware linux-headers --noconfirm

echo '>> Hacтройка точек монтирования'
genfstab -L -p -P /mnt >> /mnt/etc/fstab

echo ">> Установка"
arch-chroot /mnt sh -c "$(cat chroot-e576)" $username $hostname $pass

echo '--------------------------------------------------'
echo '|                 Перезагрузка                   |'
echo '--------------------------------------------------'
#umount -R /mnt
#reboot
