#!/bin/bash

echo '--------------------------------------------------'
echo '|                Config Install                  |'
echo '--------------------------------------------------'
username="user"
hostname="E5-576G"
pass='123'

echo '--------------------------------------------------'
echo '|              Install Arch Linux                |'
echo '--------------------------------------------------'
echo 'Install Arch Linux '$username'@'$hostname
echo '--------------------------------------------------'
echo "Server = http://mirror.yandex.ru/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
pacman -Sy sed reflector --noconfirm

echo '>> Russification...'
loadkeys ru
setfont cyr-sun16
echo -e 'KEYMAP=ru\nFONT=cyr-sun16\n' > /etc/vconsole.conf

sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen

export LANG=ru_RU.UTF-8

echo ">> Синхронизация времени"
timedatectl set-ntp true
timedatectl status

echo -e "\n"
echo '--------------------------------------------------'
echo '|             Форматирование диска               |'
echo '--------------------------------------------------'
# Типы дисков 
# MBR GPT
#  ef C12A7328-F81F-11D2-BA4B-00A0C93EC93B EFI
#  82 0657FD6D-A4AB-43C4-84E5-0933C84B4F4F SWAP linux
#     4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709 Корень linux (x86-64)
#  83 0FC63DAF-8483-4772-8E79-3D69D8477DE4 linux
#     933AC7E1-2EB4-4F13-B844-0E14E2AEF915 linux home
#   b EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 Microsoft
#   5                                      Расширенный раздел для MBR
echo 'label: gpt' | sfdisk /dev/sda    # Создать новую таблицу разделов GPT
echo 'size=2G,   type=0657FD6D-A4AB-43C4-84E5-0933C84B4F4F' | sfdisk -a /dev/sda # /dev/sda1 swap
echo 'size=256M, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B' | sfdisk -a /dev/sda # /dev/sda2 /boot
echo 'size=60G,  type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709' | sfdisk -a /dev/sda # /dev/sda3 /
echo 'size=80G,  type=EBD0A0A2-B9E5-4433-87C0-68B6B72699C7' | sfdisk -a /dev/sda # /dev/sda4 /mnt/win
echo 'size=89G,  type=933AC7E1-2EB4-4F13-B844-0E14E2AEF915' | sfdisk -a /dev/sda # /dev/sda5 /home
echo 'size=800G, type=EBD0A0A2-B9E5-4433-87C0-68B6B72699C7' | sfdisk -a /dev/sda # /dev/sda6 /mnt/public

fdisk -l

echo 'y' | mkswap /dev/sda1 -L swap
swapon /dev/sda1

echo 'y' | mkfs.ext4 /dev/sda3 -L Arch
mount /dev/sda3 /mnt

echo 'y' | mkfs.fat -F32 /dev/sda2 -n EFI
mkdir -p /mnt/boot
mount /dev/sda2 /mnt/boot

echo 'y' | mkfs.ext4 /dev/sda5 -L home
mkdir -p /mnt/home
mount /dev/sda5 /mnt/home

echo 'y' | mkfs.ntfs -Q /dev/sda4 -L win
mkdir -p /mnt/mnt/win
mount /dev/sda4 /mnt/mnt/win

echo 'y' | mkfs.ntfs -Q /dev/sda6 -L public
mkdir -p /mnt/mnt/public
mount /dev/sda6 /mnt/mnt/public

echo '--------------------------------------------------'
echo '|             Установка Arch Linux               |'
echo '--------------------------------------------------'
echo ">> Настройка Зеркал"
reflector --country Russia --country Kazakhstan --age 12 --sort rate --save /etc/pacman.d/mirrorlist

echo '>> Установка Arch GNU'
pacstrap -i /mnt base base-devel linux linux-firmware linux-headers --noconfirm

echo '>> Hacтройка точек монтирования'
genfstab -L -p -P /mnt >> /mnt/etc/fstab

echo ">> Установка"
arch-chroot /mnt sh -c "$(cat chroot-e576)" $username $hostname $pass

echo '--------------------------------------------------'
echo '|                 Перезагрузка                   |'
echo '--------------------------------------------------'
#umount -R /mnt
#reboot
