#!/bin/bash

echo '--------------------------------------------------'
echo '|                Config Install                  |'
echo '--------------------------------------------------'
username='user'
hostname='VB'
pass='123'

echo '--------------------------------------------------'
echo '|              Install Arch Linux                |'
echo '--------------------------------------------------'
echo 'Install Arch Linux '$username'@'$hostname
echo '--------------------------------------------------'
echo "Server = http://mirror.yandex.ru/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
pacman -Sy sed reflector --noconfirm

echo '>> Russification...'
loadkeys ru
setfont cyr-sun16
echo -e 'KEYMAP=ru\nFONT=cyr-sun16\n' > /etc/vconsole.conf

sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen

export LANG=ru_RU.UTF-8

echo ">> Синхронизация времени"
timedatectl set-ntp true
timedatectl status

echo -e "\n"
echo '--------------------------------------------------'
echo '|             Форматирование диска               |'
echo '--------------------------------------------------'
# Типы дисков 
# MBR GPT
#  82 0657FD6D-A4AB-43C4-84E5-0933C84B4F4F SWAP
#  ef C12A7328-F81F-11D2-BA4B-00A0C93EC93B EFI
#     4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709 Корень linux
#  83 0FC63DAF-8483-4772-8E79-3D69D8477DE4 linux
#     933AC7E1-2EB4-4F13-B844-0E14E2AEF915 linux home
#     EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 Microsoft
#   5                                      Расширенный раздел для MBR

echo 'label: gpt' | sfdisk /dev/sda
echo 'size=2G,   type=0657FD6D-A4AB-43C4-84E5-0933C84B4F4F' | sfdisk -a /dev/sda #swap
echo 'size=100M, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B' | sfdisk -a /dev/sda #/boot
echo 'size=20G,  type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709' | sfdisk -a /dev/sda #/
echo 'size=40G,  type=0FC63DAF-8483-4772-8E79-3D69D8477DE4' | sfdisk -a /dev/sda #/home

echo 'y' | mkswap /dev/sda1 -L swap
swapon /dev/sda1

echo 'y' | mkfs.ext4 /dev/sda3 -L Arch
mount /dev/sda3 /mnt

echo 'y' | mkfs.fat -F32 /dev/sda2 -n EFI
mkdir -p /mnt/boot
mount /dev/sda2 /mnt/boot

echo 'y' | mkfs.ext4 /dev/sda4 -L home
mkdir -p /mnt/home
mount /dev/sda4 /mnt/home

echo '--------------------------------------------------'
echo '|             Установка Arch Linux               |'
echo '--------------------------------------------------'
echo ">> Настройка Зеркал"
reflector --country Russia --country Kazakhstan --age 12 --sort rate --save /etc/pacman.d/mirrorlist

echo '>> Установка Arch GNU'
pacstrap -i /mnt base base-devel linux linux-firmware linux-headers --noconfirm

echo '>> Hacтройка точек монтирования'
genfstab -L -p -P /mnt >> /mnt/etc/fstab

echo ">> Установка"
arch-chroot /mnt sh -c "$(cat chroot-vb)" $username $hostname $pass

echo '--------------------------------------------------'
echo '|                 Перезагрузка                   |'
echo '--------------------------------------------------'
#umount -R /mnt
#reboot
