#!/bin/bash

# Загрузка скриптов
wget https://raw.githubusercontent.com/like913/arch-install/master/install
wget https://raw.githubusercontent.com/like913/arch-install/master/chroot
wget https://raw.githubusercontent.com/like913/arch-install/master/ru.sh

# Назначение прав на исполнениие кода
chmod +x ru.sh
chmod +x install

